// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygsSxC5bpCvc9Ew5tQhcaMtroEFqONHU',
    appId: '1:549300614762:web:b50ae2dcc06712842a3c13',
    messagingSenderId: '549300614762',
    projectId: 'leave-app-4f6d5',
    authDomain: 'leave-app-4f6d5.firebaseapp.com',
    storageBucket: 'leave-app-4f6d5.appspot.com',
    measurementId: 'G-K2TPRMNPHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6nJMrZyfSAQXTyxy3QGEmUo2yVRj_IM',
    appId: '1:549300614762:android:a1344bc37d6d440b2a3c13',
    messagingSenderId: '549300614762',
    projectId: 'leave-app-4f6d5',
    storageBucket: 'leave-app-4f6d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTIJ3JeIVgsCwe7iJj9QamRQPpHNTn2VI',
    appId: '1:549300614762:ios:efc8f759eefd04752a3c13',
    messagingSenderId: '549300614762',
    projectId: 'leave-app-4f6d5',
    storageBucket: 'leave-app-4f6d5.appspot.com',
    iosBundleId: 'com.example.leaveApp',
  );
}
